version: "3.5"

services:

  db:
      image: postgres:latest
      hostname: db
      environment:
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_USER=admin
        - POSTGRES_DB=financial
      ports:
        - "5432:5432"
      volumes:
        - ./initDB.sql:/docker-entrypoint-initdb.d/script.sql